// src/app/shared/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from 'src/app/service/auth.service';
import { Router } from '@angular/router';
import { EnumMainRoute } from 'src/app/domain/enums/enum-main-route';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export class NavbarComponent {
  constructor(private router: Router, private authService: AuthService) {}

  public handleRedirectLogoMeli(): void {
    this.router.navigate(
      this.authService.authenticatedInformation
        ? [
            EnumMainRoute.AUTHENTICATED_MELI,
            { code: this.authService.authenticatedInformation.code },
          ]
        : [EnumMainRoute.HOME],
    );
  }

  public handleRedirectEntrar(): void {
    this.router.navigate([EnumMainRoute.AUTH_MELI]);
  }

  public get userName(): string {
    return this.authService.userInformation?.first_name;
  }

  public get isAuthenticated(): boolean {
    return !!this.authService.authenticatedInformation;
  }
}

<div class="navbar w-full z-30 top-0 text-black">
  <app-container aditionalClass="flex flex-col mt-0 py-2">
    <div class="flex flex-1 justify-between">
      <img class="logo-meli" />
      <div class="flex">
        <div *ngIf="isAuthenticated" class="mr-3 self-center">
          <i class="fas fa-user self-center"></i> {{ userName }}
        </div>
        <button (click)="handleRedirectEntrar()" class="mr-3">Entre</button>
      </div>
    </div>
  </app-container>
</div>

// src/shared/components/navbar/navbar.tsx
import React from 'react';
import './styles.css';
import { ContainerComponent } from '../container/container';
import { Link } from 'react-router-dom';
import { EnumMainRoute } from 'src/domain/enums/enum-main-route';
import { AuthDataService } from 'src/services/auth-data.service';

export const NavbarComponent = () => {
  return (
    <div className="navbar w-full z-30 top-0 text-black">
      <ContainerComponent aditionalClass="flex flex-col mt-0 py-2">
        <div className="flex-1">
          <div className="grid grid-cols-4 gap-2">
            <div className="col-span-1">
              <Link
                className="self-center"
                to={{
                  pathname: EnumMainRoute.HOME,
                  search: `${
                    AuthDataService.authenticatedInformation
                      ? `?code=${AuthDataService.authenticatedInformation.code}`
                      : ''
                  }`,
                }}
              >
                <img className="logo-meli"></img>
              </Link>
            </div>

            <div className="col-span-2 sm:col-span-3 md:col-span-3 lg:col-span-2 xl:col-span-2">
              <input
                className="bg-white input-search-meli"
                type="email"
                placeholder="Buscar produtos, marcas e muitos mais..."
              />
            </div>

            <div className="col-span-1 invisible sm:invisible md:invisible lg:invisible xl:visible">
              <img
                className="frete-meli"
                src="https://http2.mlstatic.com/resources/deals/exhibitors_resources/mlb-menu-desktop-notification-picture-514db431-a640-4355-a7fb-becde26fbc9b.png"
                title="Frete grátis pelo Mercado Pontos"
                alt="Frete grátis pelo Mercado Pontos"
              />
            </div>
          </div>
        </div>

        <div className="flex-1">
          <div className="grid grid-cols-4 gap-2">
            <div className="col-span-1">1</div>

            <div className="flex justify-center col-span-2 sm:col-span-3 md:col-span-3 lg:col-span-2 xl:col-span-2">
              2
            </div>

            <div className="flex justify-end col-span-1 invisible sm:invisible md:invisible lg:invisible xl:visible">
              3
            </div>
          </div>
        </div>
      </ContainerComponent>
    </div>
  );
};
