// src/app/pages/authenticated-meli/authenticated-meli.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { AuthService } from 'src/app/service/auth.service';
import { AuthenticatedInformation } from 'src/app/domain/models/authenticated-information';

const REFERENCE_CODE_QUERY_PARAM = 'code';

@Component({
  selector: 'app-authenticated-meli',
  templateUrl: './authenticated-meli.component.html',
  styleUrls: ['./authenticated-meli.component.scss'],
})
export class AuthenticatedMeliComponent implements OnInit {
  constructor(
    private activatedRoute: ActivatedRoute,
    private authService: AuthService,
  ) {}

  ngOnInit(): void {
    this.capturarQueryParams();
  }

  private capturarQueryParams(): void {
    this.activatedRoute.queryParamMap.subscribe((paramMap: ParamMap) => {
      this.authService
        .getAuthenticatedInformation(paramMap.get(REFERENCE_CODE_QUERY_PARAM))
        .subscribe((authenticatedInformation: AuthenticatedInformation) => {
          if (authenticatedInformation) {
            this.authService.authenticatedInformation = authenticatedInformation;
          }
        });
    });
  }
}

<app-navbar></app-navbar>
<p>authenticated-meli works!</p>

// src/pages/authenticated-meli/authenticated-meli.tsx
import React from 'react';
import { useLocation } from 'react-router-dom';
import { ApiAuthMeli$ } from '../../services/mercado-livre-api';
import { AuthenticatedInformation } from '../../domain/models/authenticated-information';
import { take } from 'rxjs/operators';
import { AuthDataService } from 'src/services/auth-data.service';

const REFERENCE_CODE_QUERY_PARAM = 'code';

export const AuthenticatedMeliComponent = () => {
  const queryParams = new URLSearchParams(useLocation().search);

  const [code] = React.useState<string>(
    queryParams.get(REFERENCE_CODE_QUERY_PARAM),
  );

  ApiAuthMeli$(code)
    .pipe(take(1))
    .subscribe((authenticatedInformation: AuthenticatedInformation) => {
      AuthDataService.authenticatedInformation = authenticatedInformation;
    });

  return <div>AuthenticatedMeliComponent {code}</div>;
};
